### ISSUE TITLE
[PE-D][Tester A] Unable to delete person if name is too long

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W13-4/tp#284]
Since the deletion of items depends on specifying the full name to match items, items with long names are unable to be deleted as the UI does not fully display the name.

![image.png](https://raw.githubusercontent.com/C5hives/ped/main/files/ddeefbd7-51ac-4c90-bdff-97fed8db0ac2.png)

I am unable to delete the person with the name: "Looooooooooo..." because I do not know what the full name is. The only way around this is to clear the entire list, or if I remember the long name exactly.

A maximum length of a name could possibly be set to get around this.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: C5hives/ped#1

**Comment by ywllowsensor** [comment]
dupe issue
