### ISSUE TITLE
[PE-D][Tester D] Not enough test cases for manual testing in the DG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W13-4/tp#286]
I did not have enough example test cases in for manual testing in the developer guide. This makes it difficult to have example test cases to test.

![Screenshot 2024-11-08 at 4.14.07 PM.png](https://raw.githubusercontent.com/hooyushing/ped/main/files/ae5f8ea3-aa84-4f94-84b0-8ef297950a25.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: hooyushing/ped#1

**Comment by ywllowsensor** [comment]
dupe issue
