### ISSUE TITLE
[PE-D][Tester E] long fields are cut off

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W13-4/tp#299]
realistically, addresses can be quite long and end with a unit number etc. it would inconvenience the user to be unable to see the last few characters

![image.png](https://raw.githubusercontent.com/jiaxinnns/ped/main/files/02777ce3-a9a7-4064-b3b6-0f5bd01751b4.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: jiaxinnns/ped#9

**Comment by ywllowsensor** [comment]
dupe issue
