### ISSUE TITLE
[PE-D][Tester E] order of names matters in delete wedding operation 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W13-4/tp#313]
![hian & terry.png](https://raw.githubusercontent.com/jiaxinnns/ped/main/files/0afa2416-3f85-4a6f-8099-501dbd69938e.png)

it could be user-unfriendly to have to remember the order in which the names were saved? furthermore there is no search function for weddings which makes it hard to recall the order. maybe the 2 names can automatically be sorted and saved to be in alphabetical order

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jiaxinnns/ped#17

**Comment by ywllowsensor** [comment]
param table againnn
