### ISSUE TITLE
[PE-D][Tester E] address field accepting any value makes the app prone to typos

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W13-4/tp#322]
the user might have meant to edit job as well but forgot to place a space there, but the address field accepts it and the user needs to redo the entire command, or worse, might not realise the error since he is a fast typer and will move on to the next command quickly.

![File Help.png](https://raw.githubusercontent.com/jiaxinnns/ped/main/files/9ca585d6-ebd1-45c5-aea9-ce1d90f041c2.png)￼

![Enter command here..png](https://raw.githubusercontent.com/jiaxinnns/ped/main/files/503b8eba-cf61-4b79-8205-f456f8445f44.png)￼

the team can consider disallowing / in the address names since it is used for parsing.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jiaxinnns/ped#20

**Comment by ywllowsensor** [comment]
parameters table type shit

**Comment by ywllowsensor** [comment]
@zzibo this one also i think would fit better under the edit command itself as opposed to inside the param table. whaduyu think

**Comment by zzibo** [comment]
Personally, I find it quite difficult to avoid this
