### ISSUE TITLE
[PE-D][Tester D] Navigability of the UG is an issue

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W13-4/tp#341]
It is very difficult to scroll to the correct part of the UG quickly as there are no links back to the content page to go to the correct place easily for testing.

![Screenshot 2024-11-08 at 5.10.17 PM.png](https://raw.githubusercontent.com/hooyushing/ped/main/files/c8928698-9d08-48dc-9d36-f98ee9bc34dd.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: hooyushing/ped#18

**Comment by ywllowsensor** [comment]
can include at the top of the UG that to navigate back to ToC, they can press:
Home key (for windows/linux)
command + left arrow (for mac)

also another unrelated suggestion
if they need to search for anyth specific use ctrl-f or command-f

**Comment by zzibo** [comment]
Add tips to make navigation easier
