### ISSUE TITLE
[PE-D][Tester B] Long Input for name is not visible for the end

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W13-4/tp#348]
![Screenshot 2024-11-08 at 5.15.02 PM.png](https://raw.githubusercontent.com/JoanneHing/ped/main/files/23dfe4dd-bb49-4604-b924-8db5f47d5ea2.png)
Screenshot 2024-11-08 at 5.15.02 PM

Very long input for name become non visible and have no other ways to view it

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: JoanneHing/ped#8

**Comment by ywllowsensor** [comment]
ignore
