### ISSUE TITLE
[PE-D][Tester B] Not clear that delete will be pending until `y` or `n` is input

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W13-4/tp#359]
Operation flow
- `del n/Jeremy Eg`
- do not input `y` or `n` and proceed
- do some other operation (not including `del`)
- input `y` or `n`
- the `del/Jeremy Ng` proceed

The user might not be clear that not confirming after delete will cause the feature to be pending. And they might accidentally input `y` if they thought not putting anything is also assume operation cancel. And accidentally delete the person.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: JoanneHing/ped#11

**Comment by ywllowsensor** [comment]
can make it clearer in UG that doing any other command follwing delete will cause unexpected behaviour.
