### ISSUE TITLE
[PE-D][Tester E] delete wedding deletes the tag from all contacts, without warning

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W13-4/tp#378]
since there is confirmation for the delete command, maybe there should be one for delete wedding as well, since it might be accidentally recursively deleted from the contacts as well. the team can consider checking whether the tag is currently in use, and warn the user if so.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jiaxinnns/ped#30

**Comment by jonushzw** [comment]
add to planned enhancements
